name: Release CRX MV2

on:
  workflow_dispatch:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v6
        with:
          node-version-file: 'package.json'

      - name: Prepare
        run: pnpm ci && node scripts/action-helper.js

      - name: Build
        env:
          SYNC_DROPBOX_CLIENT_ID: ${{ secrets.SYNC_DROPBOX_CLIENT_ID }}
          SYNC_GOOGLE_DESKTOP_ID: ${{ secrets.SYNC_GOOGLE_DESKTOP_ID }}
          SYNC_GOOGLE_DESKTOP_SECRET: ${{ secrets.SYNC_GOOGLE_DESKTOP_SECRET }}
          SYNC_ONEDRIVE_CLIENT_ID: ${{ secrets.SYNC_ONEDRIVE_CLIENT_ID }}
        run: |
          mkdir -p $ASSETS_DIR $TEMP_DIR
          pnpm build

      - name: Build MV2 CRX
        if: env.PRERELEASE != 'true'
        env:
          CRX_PRIVATE_KEY: ${{ secrets.CRX_PRIVATE_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          # Rebuild manifest with `update_url` for self-hosted MV2
          TARGET=selfHosted npx gulp manifest
          node scripts/crx-helper.mjs

      - name: Upload CRX asset
        if: env.PRERELEASE != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node -e 'import("./scripts/release-helper.mjs").then(({ uploadAssets }) => uploadAssets())';

      - name: Update CRX manifest on updates branch
        if: env.PRERELEASE != 'true'
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: updates
          folder: ${{ env.TEMP_DIR }}/updates
          clean: false
          commit-message: Update CRX manifest to ${{ env.VERSION }} 🚀
